baseurl = "https://ashish.one/"
languageCode = "en-us"
title = "ashish.one"
theme = "hyde-hyde"

googleAnalytics = "UA-149424518-1"
enableRobotsTXT = true

paginate = 5

[Taxonomies]
	tag = "tags"
	topics = "topics"

[params]
	mainSections = ["post"]
	author = "Ashish Tiwari"
	title = "ashish.one"

	copyright = "ashish"
	since = "2019"

    highlightjs = true
    highlightjsstyle = "github"	

	UtterancesRepo = "ashishtiwari1993/ashish.one"
	UtterancesIssueTerm = "title"
	UtterancesTheme = "github-light"		


[params.social]
	gravatar = "atashish171@gmail.com"
	twitter = "_ashish_tiwari"
	github = "ashishtiwari1993"
	linkedin = "ashish-tiwari-a40a012b"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About me"
    url = "/about/"
    weight = -100

  [[menu.main]]
    name = "Topics"
    post = "<span class='alert'>New!</span>"
    url = "/topics/"
    weight = -99

  [[menu.main]]
    name = "Gist"
    post = "<span class='alert'>New!</span>"
    url = "/gist/"
    weight = -97

  [[menu.main]]
    name = "Talks"
    post = "<span class='alert'>New!</span>"
    url = "/talks/"
    weight = -96
