baseurl = "https://ashish.one/"
languageCode = "en-us"
title = "ashish.one"
theme = "hyde"
copyright = "Ashish Tiwari"
publishDir = "docs"
googleAnalytics = "UA-149424518-1"

[Author]
	name = "Ashish Tiwari"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "stuff by Ashish Tiwari"
	linkedin = "https://in.linkedin.com/in/ashish-tiwari-a40a012b"
	twitter = "https://twitter.com/_ashish_tiwari"
	github = "https://github.com/ashishtiwari1993"
	stackoverflow = "https://stackoverflow.com/users/6438430/ashish-tiwari"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -100

  [[menu.main]]
    name = "Blogs"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/blogs/"
    weight = -99

  [[menu.main]]
    name = "Gist"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/gist/"
    weight = -98
